/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLayout: typeof import('./components/AppLayout.vue')['default']
    BackToTop: typeof import('./components/BackToTop.vue')['default']
    CTASection: typeof import('./components/landing/CTASection.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ErrorState: typeof import('./components/ErrorState.vue')['default']
    FeatureCards: typeof import('./components/landing/FeatureCards.vue')['default']
    HeroSection: typeof import('./components/landing/HeroSection.vue')['default']
    LandingFooter: typeof import('./components/landing/LandingFooter.vue')['default']
    LandingHeader: typeof import('./components/landing/LandingHeader.vue')['default']
    LandingLayout: typeof import('./components/LandingLayout.vue')['default']
    LoadingState: typeof import('./components/LoadingState.vue')['default']
    MobileNav: typeof import('./components/MobileNav.vue')['default']
    PaperCard: typeof import('./components/PaperCard.vue')['default']
    ProductShowcase: typeof import('./components/landing/ProductShowcase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonCard: typeof import('./components/SkeletonCard.vue')['default']
    SocialProof: typeof import('./components/landing/SocialProof.vue')['default']
  }
}
